#!/bin/sh
### BEGIN INIT INFO
# Provides:          agentgui
# Required-Start:    $local_fs $network $named $portmap $remote_fs $syslog $time $all 
# Required-Stop:     $local_fs $network $named $portmap $remote_fs $syslog $time $all
# Should-Start:      mysql
# Should-Stop:       mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts and stops AgentGUI Background Service
# Description:       This script should be placed in /etc/init.d.
### END INIT INFO

#
# Author: Christian Derksen <christian.derksen@icb.uni-due.de>
#
# Please, make sure that the configuration file of Agent.GUI 
# (see /opt/agentgui/properties/agentgui.ini) is configured in the right way.
#
# In order to automatically start Agent.GUI with the system start, you can
# use the following comand (removeing is shown in the subsequent line).
# sudo update-rc.d agentgui defaults 99 10
# sudo update-rc.d -f agentgui remove
#

# ---------------------------------------------------------
# Variable settings
SERVICE_NAME=AgentGUI
NAME=agentgui
DESC="Agent.GUI Background Service"
PACKAGE=/opt/$NAME
PATH_TO_JAR=$PACKAGE/AgentGui.jar
PIDFILE=/var/run/$NAME.pid

SCRIPTNAME=/etc/init.d/$NAME
DAEMON_ARGS="--options args"

# ---------------------------------------------------------
# Exit if the package is not installed
[ -x "$PACKAGE" ] || exit 0

# ---------------------------------------------------------
# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# ---------------------------------------------------------
# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# ---------------------------------------------------------
# Agent.GUI execution, restart or shutdoen
# ---------------------------------------------------------
case "${1:-''}" in
    'start')
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PIDFILE ]; then
            nohup java -jar $PATH_TO_JAR /tmp 2>> /dev/null >> /dev/null & echo $! > $PIDFILE
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
	
    'stop')
        if [ -f $PIDFILE ]; then
            PID=$(cat $PIDFILE);
            echo "$SERVICE_NAME stoping (PID=$PID)..."
			# Delte Shutdown file of Agent.GUI first
			find $PACKAGE -name "*$PID.txt" -delete
			wait $PID
			#kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PIDFILE
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
	
    'restart')
        if [ -f $PIDFILE ]; then
            PID=$(cat $PIDFILE);
            echo "$SERVICE_NAME stoping (PID=$PID)..."
			# Delte Shutdown file of Agent.GUI first
			find $PACKAGE -name "*$PID.txt" -delete 
			# Wait until the process completion
			wait $PID
			#kill $PID;
			echo "$SERVICE_NAME stopped ...";
            rm $PIDFILE
            echo "$SERVICE_NAME starting ..."
            nohup java -jar $PATH_TO_JAR /tmp 2>> /dev/null >> /dev/null & echo $! > $PIDFILE
            echo "$SERVICE_NAME restarted ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
	
	'status'|'check')
	if [ -f $PIDFILE ]; then
	  echo "$SERVICE_NAME is running!"
	else
	  echo "$SERVICE_NAME is NOT running!"
	fi
  	;;
esac 

:
