bin.includes = plugin.xml,\
                META-INF/,\
                .,\
                /plugin_customization.ini,\
                icons/,\
                ApplicationMenues.e4xmi,\
                Application.e4xmi,\
                about.ini,\
                OSGI-INF/
src.includes = icons/,\
                plugin_customization.ini,\
                Application.e4xmi,\
                ApplicationMenues.e4xmi
source.. = src/
javacDefaultEncoding.. = UTF-8
