source.. = src/
output.. = target/classes/
bin.includes = META-INF/,\
               .,\
               properties/,\
               lib/logback-classic-1.5.38.jar,\
               lib/logback-classic-db-1.5.32.jar,\
               lib/logback-core-1.5.32-tests.jar,\
               lib/logback-core-1.5.38.jar,\
               lib/logback-core-db-1.5.32.jar,\
               lib/slf4j-api-2.0.17.jar
