bin.includes = META-INF/,\
               .,\
               lib/,\
               lib/docker-java-api-3.7.0.jar,\
               lib/docker-java-core-3.7.0.jar,\
               lib/docker-java-transport-3.7.0.jar,\
               lib/error_prone_annotations-2.36.0.jar,\
               lib/failureaccess-1.0.3.jar,\
               lib/j2objc-annotations-3.0.0.jar,\
               lib/jspecify-1.0.0.jar,\
               lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
